### PR TITLE
haha fuckin kill me XD

### PR DESCRIPTION
**Pull request by Getindor**
im on wangblows at the moment so i figured I'd compile a windows version xD maybe some newfags who dont know how to compile will appreciate it :^)

I understand if you don't accept, stay noided.

<3

### CODE REVIEW

**Comment by LandonPowell** [comment]
>making life easier for Windows users
tbh I want to make using Windows as hard as possible so people will want to switch.

**Comment by Getindor** [comment]
tru

**Comment by Getindor** [comment]
its easier to install on gnu/hurd

**Comment by LandonPowell** [comment]
I should pointlessly use some GNU coreutil directly from the binary just to make DY not windows compatible kek.

**Comment by Getindor** [comment]
do it !!!

**Comment by Getindor** [comment]
gnu/deviousyarn

**Comment by Getindor** [comment]
# all pull requests are appreciated

**Pull request closed without merging**
